DROP TABLE IF EXISTS transaksi;
DROP TABLE IF EXISTS barang;

CREATE TABLE barang (
  id TEXT PRIMARY KEY,
  nama TEXT NOT NULL,
  sku TEXT UNIQUE NOT NULL,
  jumlah INTEGER NOT NULL,
  kategori TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaksi (
  id TEXT PRIMARY KEY,
  sku TEXT NOT NULL,
  nama_barang TEXT NOT NULL,
  tipe TEXT NOT NULL,
  jumlah INTEGER NOT NULL,
  tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

