name = "gudang-cloud"
main = "src/index.js"
compatibility_date = "2026-09-02"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "gudang_db"
database_id = "YOUR_D1_DATABASE_ID"
